routes/admin.php
        Route::get('edit','ProfileController@edit')->name('edit');
        Route::post('update','ProfileController@update')->name('update');
    });

    //tests and its components
    Route::resource('tests','TestsController');
    Route::get('get_tests','TestsController@ajax')->name('get_tests');//datatable

    //countries
    Route::resource('countries','CountriesController');
    Route::post('get_country_details','CountriesController@ajax')->name('get_country_details');

    //antibiotics
    Route::resource('antibiotics','AntibioticsController');
    Route::get('get_antibiotics','AntibioticsController@ajax')->name('get_antibiotics');

    //patients
    Route::resource('patients','PatientsController');
    Route::get('get_patients','PatientsController@ajax')->name('get_patients');
    Route::get('patients_export','PatientsController@export')->name('patients.export');
    Route::get('patients_download_template','PatientsController@download_template')->name('patients.download_template');
    Route::post('patients_import','PatientsController@import')->name('patients.import');

    //labs
    Route::resource('labs','LabsController');
    Route::get('get_labs','LabsController@ajax')->name('get_labs');
    Route::post('get_lab_centers','LabsController@get_lab_centers')->name('get_lab_centers');
    Route::get('labs_export','LabsController@export')->name('labs.export');
    Route::get('labs_download_template','LabsController@download_template')->name('labs.download_template');
    Route::post('labs_import','LabsController@import')->name('labs.import');

    //Airlines
    Route::resource('airlines','AirlinesController');
    Route::get('get_airlines','AirlinesController@ajax')->name('get_airlines');
    Route::get('labs_export','AirlinesController@export')->name('airlines.export');
    Route::get('labs_download_template','AirlinesController@download_template')->name('airlines.download_template');
    Route::post('labs_import','AirlinesController@import')->name('airlines.import');

	//Discount Role
    Route::resource('discountrole','DiscountRoleController');
    Route::get('get_discountrole','DiscountRoleController@ajax')->name('get_discountrole');
    Route::get('discountrole_export','DiscountRoleController@export')->name('discountrole.export');
    Route::get('discountrole_download_template','DiscountRoleController@download_template')->name('discountrole.download_template');
    Route::post('discountrole_import','DiscountRoleController@import')->name('discountrole.import');

    //centers
    Route::resource('centers','CentersController');
    Route::get('get_centers','CentersController@ajax')->name('get_centers');
    Route::get('centers_export','CentersController@export')->name('centers.export');
    Route::get('centers_download_template','CentersController@download_template')->name('centers.download_template');
    Route::post('centers_import','CentersController@import')->name('centers.import');

    //Test Unit
    Route::resource('units','UnitsController');
    Route::get('get_units','UnitsController@ajax')->name('get_units');
    Route::get('units_export','UnitsController@export')->name('units.export');
    Route::get('units_download_template','UnitsController@download_template')->name('units.download_template');
    Route::post('units_import','CentersController@import')->name('units.import');

    //Faranchises
    Route::resource('faranchises','FaranchisesController');
    Route::get('get_faranchises','FaranchisesController@ajax')->name('get_faranchises');
    Route::get('faranchises_export','FaranchisesController@export')->name('faranchises.export');
    Route::get('faranchises_download_template','FaranchisesController@download_template')->name('faranchises.download_template');
    Route::post('faranchises_import','FaranchisesController@import')->name('faranchises.import');

    //Supervisors Shift
    Route::resource('supervisorshift','SupervisorshiftController');
    Route::get('get_supervisorshift','SupervisorshiftController@ajax')->name('get_supervisorshift');
    Route::get('supervisorshift_export','SupervisorshiftController@export')->name('supervisorshift_export');
    Route::get('supervisorshift_download_template','SupervisorshiftController@download_template')->name('supervisorshift.download_template');
    Route::post('supervisorshift_import','SupervisorshiftController@import')->name('supervisorshift.import');

    //Users Shift
    Route::resource('usershift','UsershiftController');
    Route::get('get_usershift','UsershiftController@ajax')->name('usershift');
    Route::get('usershift_export','UsershiftController@export')->name('usershift_export');
    Route::get('usershift_download_template','UsershiftController@download_template')->name('usershift.download_template');
    Route::post('usershift_import','UsershiftController@import')->name('usershift.import');

    //Sample
    Route::resource('sample','SampleController');
    Route::get('get_sample','SampleController@ajax')->name('sample');

    //Patterns
    Route::resource('pattern','PatternController');
    Route::get('get_pattern','PatternController@ajax')->name('pattern');
    Route::get('pattern_export','PatternController@export')->name('pattern_export');
    Route::get('pattern_download_template','PatternController@download_template')->name('pattern.download_template');
    Route::post('pattern_import','PatternController@import')->name('pattern.import');

    //Age Classification
    Route::resource('age_classification','AgeClassificationController');
    Route::get('get_age_classification','AgeClassificationController@ajax')->name('age_classification');
    Route::get('age_classification_export','AgeClassificationController@export')->name('age_classification_export');
    Route::get('age_classification_download_template','AgeClassificationController@download_template')->name('age_classification.download_template');
    Route::post('age_classification_import','AgeClassificationController@import')->name('age_classification.import');

    //Normal Range Heading
    Route::resource('normal_range_heading','NormalRangeHeadingController');
    Route::get('get_normal_range_heading','NormalRangeHeadingController@ajax')->name('normal_range_heading');
    Route::get('normal_range_heading_export','NormalRangeHeadingController@export')->name('normal_range_heading_export');
    Route::get('normal_range_heading_download_template','NormalRangeHeadingController@download_template')->name('normal_range_heading.download_template');
    Route::post('normal_range_heading_import','NormalRangeHeadingController@import')->name('normal_range_heading.import');

	//Product Registration
    Route::resource('product_registration','ProductRegistrationController');
    Route::get('get_product_registration','ProductRegistrationController@ajax')->name('product_registration');
    Route::get('product_registration_export','ProductRegistrationController@export')->name('product_registration_export');
    Route::get('product_registration_download_template','ProductRegistrationController@download_template')->name('product_registration.download_template');
    Route::post('product_registration_import','ProductRegistrationController@import')->name('product_registration.import');

	//Morphology Registration
    Route::resource('morphology_registration','MorphologyRegistrationController');
    Route::get('get_morphology_registration','MorphologyRegistrationController@ajax')->name('morphology_registration');
    Route::get('morphology_registration_export','MorphologyRegistrationController@export')->name('morphology_registration_export');
    Route::get('morphology_registration_download_template','MorphologyRegistrationController@download_template')->name('morphology_registration.download_template');
    Route::post('morphology_registration_import','MorphologyRegistrationController@import')->name('morphology_registration.import');

	//CBC Remarks
    Route::resource('cbc_remarks','CbcRemarksController');
    Route::get('get_cbc_remarks','CbcRemarksController@ajax')->name('cbc_remarks');
    Route::get('cbc_remarks_export','CbcRemarksController@export')->name('cbc_remarks_export');
    Route::get('cbc_remarks_download_template','CbcRemarksController@download_template')->name('cbc_remarks.download_template');
    Route::post('cbc_remarks_import','CbcRemarksController@import')->name('cbc_remarks.import');

	// Package Registrations
    Route::resource('package_registrations','PackageRegistrationsController');
    Route::get('get_package_registrations','PackageRegistrationsController@ajax')->name('package_registrations');
    Route::get('package_registrations_export','PackageRegistrationsController@export')->name('package_registrations_export');
    Route::get('package_registrations_download_template','PackageRegistrationsController@download_template')->name('package_registrations.download_template');
    Route::post('package_registrations_import','PackageRegistrationsController@import')->name('package_registrations.import');

	//Customer Registration
    Route::resource('customer_registration','CustomerRegistrationController');
    Route::get('get_customer_registration','CustomerRegistrationController@ajax')->name('customer_registration');
	Route::post('get_party_centers','CustomerRegistrationController@get_party_centers')->name('get_party_centers');
    Route::get('customer_registration_export','CustomerRegistrationController@export')->name('customer_registration_export');
    Route::get('customer_registration_download_template','CustomerRegistrationController@download_template')->name('customer_registration.download_template');
    Route::post('customer_registration_import','CustomerRegistrationController@import')->name('customer_registration.import');
    Route::post('customer_registration_doc','CustomerRegistrationController@doc_upload')->name('customer_registration.doc_upload');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware'=>['Install','Locale']],function(){
  include('admin.php');
  include('ajax.php');
  include('patient.php');
});

Route::get('change_locale/{lang}','HomeController@change_locale')->name('change_locale');

Route::get('clear-cache',function(){
  \Artisan::call('cache:clear');
  \Artisan::call('config:clear');
  \Artisan::call('view:clear');
});

resources/views/admin/faranchises/_action.blade.php
@can('edit_patient')
    <a class="btn btn-primary btn-sm" href="{{route('admin.faranchises.edit',$patient->id)}}">
        <i class="fa fa-edit" aria-hidden="true"></i>
    </a>
@endcan

@can('delete_patient')
    <form method="POST" action="{{route('admin.faranchises.destroy',$patient->id)}}" class="d-inline">
        <input type="hidden" name="_method" value="delete">
        <button type="submit" class="btn btn-danger btn-sm delete_patient">
            <i class="fa fa-trash"></i>
        </button>
    </form>
@endcan

resources/views/admin/faranchises/_due.blade.php
@if($patient['due']>0)
    <span class="text-danger text-bold">
        {{formated_price($patient['due'])}}
    </span>
@else 
    <span class="text-success">
        {{formated_price($patient['due'])}}
    </span>
@endif

resources/views/admin/faranchises/_export.blade.php
<table>
    <thead>
        <tr>
            <th align="center" width="10">{{__('id')}}</th>
            <th align="center" width="20">{{__('Code')}}</th>
            <th align="center" width="20">{{__('Name')}}</th>
            <th align="center" width="20">{{__('Gender')}}</th>
            <th align="center" width="20">{{__('DOB')}}</th>
            <th align="center" width="20">{{__('Age')}}</th>
            <th align="center" width="20">{{__('Phone')}}</th>
            <th align="center" width="20">{{__('Email')}}</th>
            <th align="center" width="20">{{__('Address')}}</th>
            <th align="center" width="20">{{__('Total')}}</th>
            <th align="center" width="20">{{__('Paid')}}</th>
            <th align="center" width="20">{{__('Due')}}</th>
        </tr>
    </thead>
    <tbody>
    @foreach($patients as $patient)
        <tr>
            <td align="center">{{ $patient['id'] }}</td>
            <td align="center">{{ $patient['code'] }}</td>
            <td align="center">{{ $patient['name'] }}</td>
            <td align="center">{{ $patient['gender'] }}</td>
            <td align="center">{{ date('d-m-Y',strtotime($patient['dob'])) }}</td>
            <td align="center">{{ $patient['age'] }}</td>
            <td align="center">{{ (string) $patient['phone'] }}</td>
            <td align="center">{{ $patient['email'] }}</td>
            <td align="center">{{ $patient['address'] }}</td>
            <td align="center">{{ formated_price($patient['total']) }}</td>
            <td align="center">{{ formated_price($patient['paid']) }}</td>
            <td align="center" style="@if($patient['due']>0) color:red; @else color:#28a745; @endif">{{ formated_price($patient['due']) }}</td>
        </tr>
    @endforeach
    </tbody>
</table>

resources/views/admin/faranchises/create.blade.php
@extends('layouts.app')

@section('title')
{{__('Create Faranchise')}}
@endsection

@section('breadcrumb')
<div class="content-header">
    <div class="container-fluid" id="myHeaderLinks">
      <div class="row mb-2">
        <div class="col-sm-12">
          <h1 class="m-0 text-dark">
            <i class="nav-icon fas fa-user-injured"></i>
            {{__('Faranchises')}}
          </h1>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
@endsection

@section('content')
<div class="card card-primary" id="page-wrap">
    <div class="card-header">
      <h3 class="card-title">{{__('General')}}</h3>
    </div>
    <form method="POST" action="{{route('admin.faranchises.store')}}"  enctype="multipart/form-data"  id="form">
        <!-- /.card-header -->
        <div class="card-body">
            @csrf
            @include('admin.faranchises._form')
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">{{__('Save')}}</button>
        </div>
    </form>

</div>
@endsection
@section('scripts')
  <script src="{{url('public/js/admin/faranchises.js')}}"></script>
@endsection

resources/views/admin/faranchises/edit.blade.php
@extends('layouts.app')

@section('title')
{{__('Edit Faranchise')}}
@endsection

@section('breadcrumb')

<div class="content-header">
    <div class="container-fluid" id="myHeaderLinks">
      <div class="row mb-2">
        <div class="col-sm-12">
          <h1 class="m-0 text-dark">
            <i class="nav-icon fas fa-user-injured"></i>
            {{__('Faranchises')}}
          </h1>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
@endsection

@section('content')
<div class="card card-primary">
    <div class="card-header">
      <h3 class="card-title">{{__('Edit Faranchise')}}</h3>
    </div>
    <!-- /.card-header -->
    <form method="POST" action="{{route('admin.faranchises.update',$patient->id)}}"  enctype="multipart/form-data"  id="form">
        <!-- /.card-header -->
        <div class="card-body">
            @csrf
            @method('put')
            @include('admin.faranchises._form')
        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">{{__('Save')}}</button>
        </div>
    </form>
    <!-- /.card-body -->
  </div>

@endsection
@section('scripts')
  <script src="{{url('public/js/admin/faranchises.js')}}"></script>
@endsection

resources/views/admin/faranchises/index.blade.php
@extends('layouts.app')

@section('title')
{{__('Labs')}}
@endsection

@section('breadcrumb')
<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark">
            <i class="nav-icon fas fa-user-injured"></i>
            {{__('Faranchises')}}
          </h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{route('admin.index')}}">{{__('Home')}}</a></li>
            <li class="breadcrumb-item active">{{__('Faranchises')}}</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
@endsection

@section('content')
<div class="card card-primary card-outline">
    <div class="card-header">
      <h3 class="card-title">{{__('Faranchises Table')}}</h3>
      @can('create_patient')
      <a href="{{route('admin.faranchises.create')}}" class="btn btn-primary btn-sm float-right">
       <i class="fa fa-plus"></i> {{__('Create')}} 
      </a>
      @endcan
    </div>
    <!-- /.card-header -->
    <div class="card-body">
     
	 {{--
      <div class="row">
        <div class="col-lg-12">
          <!-- Tools -->
          <div id="accordion">
            <div class="card card-info">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" class="btn btn-primary collapsed" aria-expanded="false">
                <i class="fas fa-file-excel"></i>
                {{__('Import / Export')}}
              </a>
              <div id="collapseOne" class="panel-collapse in collapse">
                <div class="card-body">
                  <div class="row">
                    <div class="col-lg-12 text-center">
                      <a class="btn btn-success" href="{{route('admin.faranchises.export')}}">
                        <i class="fa fa-file-excel"></i>
                        {{__('Export')}}
                      </a>
                      <a class="btn btn-success" href="{{route('admin.faranchises.download_template')}}">
                        <i class="fa fa-file-excel"></i>
                        {{__('Download template')}}
                      </a>
                    </div>
                    <div class="col-lg-12">
                      <!-- import form -->
                      <form action="{{route('admin.faranchises.import')}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="row mt-3">
                          <div class="col-lg-12">
                            <div class="card card-primary">
                              <div class="card-header">
                                <h5 class="card-title">
                                    {{__('Import')}}
                                </h5>
                              </div>
                              <div class="card-body">
                                <div class="input-group">
                                  <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="exampleInputFile" name="import" required>
                                    <label class="custom-file-label" for="exampleInputFile">{{__('Choose file')}}</label>
                                  </div>
                                </div>
                              </div>
                              <div class="card-footer">
                                <button type="submit" class="btn btn-primary">
                                  <i class="fa fa-check"></i>
                                  {{__('Import')}}
                                </button>
                              </div>
                            </div>
                          </div>
                        </div>
                      </form>
                      <!-- /import form -->
                    </div>
                    
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- \Tools -->
        </div>
      </div>

	  --}}
      <div class="row">
        <div class="col-lg-12 table-responsive">
          <table id="table" class="table table-striped table-hover table-bordered" width="100%">
            <thead>
            <tr>
              <th>Franchise ID</th>
              <th>{{__('Organization')}}</th>
              <th>{{__('Name (English)')}}</th>
              <th>{{__('Name (Local)')}}</th>
              <th>{{__('Lab')}}</th>
              <th>{{__('Country')}}</th>
              <th>{{__('Province')}}</th>
              <th>{{__('City')}}</th>
              <th width="100px">{{__('Action')}}</th>
            </tr>
            </thead>
            <tbody>
                
            </tbody>
          </table>

        </div>
      </div>
    </div>
    <!-- /.card-body -->
  </div>

@endsection
@section('scripts')
  <script src="{{url('public/js/admin/faranchises.js')}}"></script>
@endsection