routes/admin.php
    Route::get('centers_download_template','CentersController@download_template')->name('centers.download_template');
    Route::post('centers_import','CentersController@import')->name('centers.import');

    //Test Unit
    Route::resource('units','UnitsController');
    Route::get('get_units','UnitsController@ajax')->name('get_units');
    Route::get('units_export','UnitsController@export')->name('units.export');
    Route::get('units_download_template','UnitsController@download_template')->name('units.download_template');
    Route::post('units_import','CentersController@import')->name('units.import');

    //Faranchises
    Route::resource('faranchises','FaranchisesController');
    Route::get('get_faranchises','FaranchisesController@ajax')->name('get_faranchises');
    Route::get('faranchises_export','FaranchisesController@export')->name('faranchises.export');
    Route::get('faranchises_download_template','FaranchisesController@download_template')->name('faranchises.download_template');
    Route::post('faranchises_import','FaranchisesController@import')->name('faranchises.import');

    //Supervisors Shift
    Route::resource('supervisorshift','SupervisorshiftController');
    Route::get('get_supervisorshift','SupervisorshiftController@ajax')->name('get_supervisorshift');
    Route::get('supervisorshift_export','SupervisorshiftController@export')->name('supervisorshift_export');
    Route::get('supervisorshift_download_template','SupervisorshiftController@download_template')->name('supervisorshift.download_template');
    Route::post('supervisorshift_import','SupervisorshiftController@import')->name('supervisorshift.import');

    //Users Shift
    Route::resource('usershift','UsershiftController');
    Route::get('get_usershift','UsershiftController@ajax')->name('usershift');
    Route::get('usershift_export','UsershiftController@export')->name('usershift_export');
    Route::get('usershift_download_template','UsershiftController@download_template')->name('usershift.download_template');
    Route::post('usershift_import','UsershiftController@import')->name('usershift.import');

    //Sample
    Route::resource('sample','SampleController');
    Route::get('get_sample','SampleController@ajax')->name('sample');

    //Patterns
    Route::resource('pattern','PatternController');
    Route::get('get_pattern','PatternController@ajax')->name('pattern');
    Route::get('pattern_export','PatternController@export')->name('pattern_export');
    Route::get('pattern_download_template','PatternController@download_template')->name('pattern.download_template');
    Route::post('pattern_import','PatternController@import')->name('pattern.import');

    //Age Classification
    Route::resource('age_classification','AgeClassificationController');
    Route::get('get_age_classification','AgeClassificationController@ajax')->name('age_classification');
    Route::get('age_classification_export','AgeClassificationController@export')->name('age_classification_export');
    Route::get('age_classification_download_template','AgeClassificationController@download_template')->name('age_classification.download_template');
    Route::post('age_classification_import','AgeClassificationController@import')->name('age_classification.import');

    //Normal Range Heading
    Route::resource('normal_range_heading','NormalRangeHeadingController');
    Route::get('get_normal_range_heading','NormalRangeHeadingController@ajax')->name('normal_range_heading');
    Route::get('normal_range_heading_export','NormalRangeHeadingController@export')->name('normal_range_heading_export');
    Route::get('normal_range_heading_download_template','NormalRangeHeadingController@download_template')->name('normal_range_heading.download_template');
    Route::post('normal_range_heading_import','NormalRangeHeadingController@import')->name('normal_range_heading.import');

	//Product Registration
    Route::resource('product_registration','ProductRegistrationController');
    Route::get('get_product_registration','ProductRegistrationController@ajax')->name('product_registration');
    Route::get('product_registration_export','ProductRegistrationController@export')->name('product_registration_export');
    Route::get('product_registration_download_template','ProductRegistrationController@download_template')->name('product_registration.download_template');
    Route::post('product_registration_import','ProductRegistrationController@import')->name('product_registration.import');

	//Morphology Registration
    Route::resource('morphology_registration','MorphologyRegistrationController');
    Route::get('get_morphology_registration','MorphologyRegistrationController@ajax')->name('morphology_registration');
    Route::get('morphology_registration_export','MorphologyRegistrationController@export')->name('morphology_registration_export');
    Route::get('morphology_registration_download_template','MorphologyRegistrationController@download_template')->name('morphology_registration.download_template');
    Route::post('morphology_registration_import','MorphologyRegistrationController@import')->name('morphology_registration.import');

	//CBC Remarks
    Route::resource('cbc_remarks','CbcRemarksController');
    Route::get('get_cbc_remarks','CbcRemarksController@ajax')->name('cbc_remarks');
    Route::get('cbc_remarks_export','CbcRemarksController@export')->name('cbc_remarks_export');
    Route::get('cbc_remarks_download_template','CbcRemarksController@download_template')->name('cbc_remarks.download_template');
    Route::post('cbc_remarks_import','CbcRemarksController@import')->name('cbc_remarks.import');

	// Package Registrations
    Route::resource('package_registrations','PackageRegistrationsController');
    Route::get('get_package_registrations','PackageRegistrationsController@ajax')->name('package_registrations');
    Route::get('package_registrations_export','PackageRegistrationsController@export')->name('package_registrations_export');
    Route::get('package_registrations_download_template','PackageRegistrationsController@download_template')->name('package_registrations.download_template');
    Route::post('package_registrations_import','PackageRegistrationsController@import')->name('package_registrations.import');

	//Customer Registration
    Route::resource('customer_registration','CustomerRegistrationController');
    Route::get('get_customer_registration','CustomerRegistrationController@ajax')->name('customer_registration');
	Route::post('get_party_centers','CustomerRegistrationController@get_party_centers')->name('get_party_centers');
    Route::get('customer_registration_export','CustomerRegistrationController@export')->name('customer_registration_export');
    Route::get('customer_registration_download_template','CustomerRegistrationController@download_template')->name('customer_registration.download_template');
    Route::post('customer_registration_import','CustomerRegistrationController@import')->name('customer_registration.import');
    Route::post('customer_registration_doc','CustomerRegistrationController@doc_upload')->name('customer_registration.doc_upload');
    Route::post('customer_registration_doc_delete','CustomerRegistrationController@doc_delete')->name('customer_registration.doc_delete');

    //Customer Registration Lab
    Route::resource('customer_registration_lab','CustomerRegistrationLabController');

    //Customer Registration Centers
    Route::resource('customer_registration_center','CustomerRegistrationCenterController');

    //Customer Registration Price List
    Route::resource('customer_price_list','CustomerRegistrationPriceListController');
    Route::get('get_customer_price_list','CustomerRegistrationPriceListController@ajax')->name('customer_price_list');

	//Customer Registration Price List
    Route::resource('customer_price_list_discount','CustomerRegistrationPriceListDiscountController');

	//Faranchise Price List
    Route::resource('faranchise_price_list','FaranchisePriceListController');
    Route::get('get_faranchise_price_list','FaranchisePriceListController@ajax')->name('faranchise_price_list');

    //Faranchise Registration Price List
    Route::resource('faranchise_price_list_discount','FaranchisePriceListDiscountController');


    //departments
    Route::resource('departments','DepartmentsController');
    Route::get('get_departments','DepartmentsController@ajax')->name('get_departments');
    Route::get('departments_export','DepartmentsController@export')->name('departments.export');
    Route::get('departments_download_template','DepartmentsController@download_template')->name('departments.download_template');
    Route::post('departments_import','DepartmentsController@import')->name('departments.import');

    //specialization
    Route::resource('specializations','SpecializationsController');
    Route::get('get_specializations','SpecializationsController@ajax')->name('get_specializations');
    Route::get('specializations_export','SpecializationsController@export')->name('specializations.export');
    Route::get('specializations_download_template','SpecializationsController@download_template')->name('specializations.download_template');
    Route::post('specializations_import','SpecializationsController@import')->name('specializations.import');

    //organizations
    Route::resource('organizations','OrganizationController');
    Route::get('get_organizations','OrganizationController@ajax')->name('get_organizations');
    Route::get('organizations_export','OrganizationController@export')->name('organizations.export');
    Route::get('organizations_download_template','OrganizationController@download_template')->name('organizations.download_template');
    Route::post('organizations_import','OrganizationController@import')->name('organizations.import');

    //cultures
    Route::resource('cultures','CulturesController');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware'=>['Install','Locale']],function(){
  include('admin.php');
  include('ajax.php');
  include('patient.php');
});

Route::get('change_locale/{lang}','HomeController@change_locale')->name('change_locale');

Route::get('clear-cache',function(){
  \Artisan::call('cache:clear');
  \Artisan::call('config:clear');
  \Artisan::call('view:clear');
});

app/Models/NormalRangeHeading.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\Traits\LogsActivity;

class NormalRangeHeading extends Model
{
    use SoftDeletes;
    use LogsActivity;

    public $guarded=[];
    
    public function getDescriptionForEvent(string $eventName): string
    {
        return "Doctor was {$eventName}";
    }
}

app/Http/Controllers/Admin/NormalRangeHeadingController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\NormalRangeHeading;
use App\Http\Requests\Admin\NormalRangeHeadingRequest;
use App\Http\Requests\Admin\ExcelImportRequest;
use App\Exports\PatientExport;
use App\Imports\PatientImport;
use Str;
use DataTables;
use Excel;
use DB;
class NormalRangeHeadingController extends Controller
{
    /**
     * assign roles
     */
    public function __construct()
    {
        $this->middleware('can:view_patient',     ['only' => ['index', 'show', 'ajax']]);
        $this->middleware('can:create_patient',   ['only' => ['create', 'store']]);
        $this->middleware('can:edit_patient',     ['only' => ['edit', 'update']]);
        $this->middleware('can:delete_patient',   ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
		
        $patients=NormalRangeHeading::all();
        return view('admin.normal_range_heading.index');
    }

    /**
    * get patients datatable
    *
    * @access public
    * @var  @Request $request
    */
    public function ajax(Request $request)
    {
		
		$getData = DB::table('normal_range_headings')
		->select('normal_range_headings.*', DB::raw('(CASE 
		WHEN normal_range_headings.status = 0 THEN "In-Active" 
		WHEN normal_range_headings.status = 1 THEN "Active" 
		WHEN normal_range_headings.status = 2 THEN "Suspend" 
		ELSE "Close" END) AS status_label')); 
		
		return DataTables::of($getData)
        ->addColumn('action',function($patient){
			//$patient = (object)$patient;
            return view('admin.normal_range_heading._action',compact('patient'));
        })->make(true); 
		
		
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
		$data = array();
		return view('admin.normal_range_heading.create',compact('data'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(NormalRangeHeadingRequest $request)
    {
        $patient=NormalRangeHeading::create([
            'name_eng'=>$request->name_eng,
            'name_local'=>$request->name_local,
			'status'=>$request->status,
        ]);

        //send patient code notification
        //send_notification('patient_code',$patient);

        session()->flash('success','Normal Range Heading created successfully');

        return redirect()->route('admin.normal_range_heading.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
		$data = array();
        $patient=NormalRangeHeading::findOrFail($id);
		
        return view('admin.normal_range_heading.edit',compact('patient','data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(NormalRangeHeadingRequest $request, $id)
    {
        $patient=NormalRangeHeading::findOrFail($id);
		
        $patient->update([
            'name_eng'=>$request->name_eng,
            'name_local'=>$request->name_local,
			'status'=>$request->status,
        ]);

        session()->flash('success','Normal Range Heading data updated successfully');

        return redirect()->route('admin.normal_range_heading.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table('normal_range_headings')->where('id', '=', $id)->delete();
        session()->flash('success',__('Normal Range Heading deleted successfully'));
        return redirect()->route('admin.normal_range_heading.index');
    }

    /**
    * Export patients
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function export()
    {
        ob_end_clean(); // this
        ob_start(); // and this
        return Excel::download(new PatientExport, 'patients.xlsx');
    }

    /**
    * Import patients
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function import(ExcelImportRequest $request)
    {
        if($request->hasFile('import'))
        {
            ob_end_clean(); // this
            ob_start(); // and this
            Excel::import(new PatientImport, $request->file('import'));
        }

        session()->flash('success',__('Patients imported successfully'));

        return redirect()->back();
    }

    /**
    * Download patients template
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function download_template()
    {
        ob_end_clean(); // this
        ob_start(); // and this
        return response()->download(storage_path('app/public/patients_template.xlsx'),'patients_template.xlsx');
    }
}

resources/views/admin/normal_range_heading/_action.blade.php
@can('edit_patient')
    <a class="btn btn-primary btn-sm" href="{{route('admin.normal_range_heading.edit',$patient->id)}}">
        <i class="fa fa-edit" aria-hidden="true"></i>
    </a>
@endcan

@can('delete_patient')
    <form method="POST" action="{{route('admin.normal_range_heading.destroy',$patient->id)}}" class="d-inline">
        <input type="hidden" name="_method" value="delete">
        <button type="submit" class="btn btn-danger btn-sm delete_patient">
            <i class="fa fa-trash"></i>
        </button>
    </form>
@endcan

resources/views/admin/normal_range_heading/_due.blade.php
@if($patient['due']>0)
    <span class="text-danger text-bold">
        {{formated_price($patient['due'])}}
    </span>
@else 
    <span class="text-success">
        {{formated_price($patient['due'])}}
    </span>
@endif

resources/views/admin/normal_range_heading/_export.blade.php
<table>
    <thead>
        <tr>
            <th align="center" width="10">{{__('id')}}</th>
            <th align="center" width="20">{{__('Code')}}</th>
            <th align="center" width="20">{{__('Name')}}</th>
            <th align="center" width="20">{{__('Gender')}}</th>
            <th align="center" width="20">{{__('DOB')}}</th>
            <th align="center" width="20">{{__('Age')}}</th>
            <th align="center" width="20">{{__('Phone')}}</th>
            <th align="center" width="20">{{__('Email')}}</th>
            <th align="center" width="20">{{__('Address')}}</th>
            <th align="center" width="20">{{__('Total')}}</th>
            <th align="center" width="20">{{__('Paid')}}</th>
            <th align="center" width="20">{{__('Due')}}</th>
        </tr>
    </thead>
    <tbody>
    @foreach($patients as $patient)
        <tr>
            <td align="center">{{ $patient['id'] }}</td>
            <td align="center">{{ $patient['code'] }}</td>
            <td align="center">{{ $patient['name'] }}</td>
            <td align="center">{{ $patient['gender'] }}</td>
            <td align="center">{{ date('d-m-Y',strtotime($patient['dob'])) }}</td>
            <td align="center">{{ $patient['age'] }}</td>
            <td align="center">{{ (string) $patient['phone'] }}</td>
            <td align="center">{{ $patient['email'] }}</td>
            <td align="center">{{ $patient['address'] }}</td>
            <td align="center">{{ formated_price($patient['total']) }}</td>
            <td align="center">{{ formated_price($patient['paid']) }}</td>
            <td align="center" style="@if($patient['due']>0) color:red; @else color:#28a745; @endif">{{ formated_price($patient['due']) }}</td>
        </tr>
    @endforeach
    </tbody>
</table>

resources/views/admin/normal_range_heading/_form.blade.php
<div class="row">
    <div class="col-lg-6">
       <div class="form-group">
        <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">
                  <i class="fa fa-user"></i>
              </span>
            </div>
            <input type="text" class="form-control" placeholder="{{__('Id *')}}" name="id" id="id" @if(isset($patient)) value="{{$patient->id}}" @endif readonly>
        </div>
       </div>
    </div>
	
	<div class="col-lg-6">
       <div class="form-group">
        <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">
                  <i class="fa fa-user"></i>
              </span>
            </div>
            <input type="text" class="form-control" placeholder="{{__('Name (English) *')}}" name="name_eng" id="name_eng" @if(isset($patient)) value="{{$patient->name_eng}}" @endif required>
        </div>
       </div>
    </div>

	<div class="col-lg-6">
       <div class="form-group">
        <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">
                  <i class="fa fa-user"></i>
              </span>
            </div>
            <input type="text" class="form-control" placeholder="{{__('Name (Local)')}}" name="name_local" id="name_local" @if(isset($patient)) value="{{$patient->name_local}}" @endif >
        </div>
       </div>
    </div>
	
	 <div class="col-lg-6">
        <div class="form-group">
            <div class="form-group">
                <div class="input-group">
                    <div class="input-group-prepend">
                      <span class="input-group-text" id="basic-addon1">
                        <i class="fas fa-flag"></i>
                      </span>
                    </div>
                    <select class="form-control" name="status" placeholder="{{__('Status')}}" id="status" required>
                       <option value="0"  @if(isset($patient)&&$patient['status']==0) selected @endif >In Active</option>
                       <option value="1"  @if(isset($patient)&&$patient['status']==1) selected @endif >Active</option>
                       <option value="2"  @if(isset($patient)&&$patient['status']==2) selected @endif >Suspend</option>
                       <option value="3"  @if(isset($patient)&&$patient['status']==3) selected @endif >Close</option>
                    </select>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/admin/normal_range_heading/create.blade.php
@extends('layouts.app')

@section('title')
{{__('Create Normal Range Heading')}}
@endsection

@section('breadcrumb')
<div class="content-header">
    <div class="container-fluid" id="myHeaderLinks">
      <div class="row mb-2">
        <div class="col-sm-12">
          <h1 class="m-0 text-dark">
            <i class="nav-icon fas fa-user-injured"></i>
            {{__('Normal Range Heading')}}
          </h1>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
@endsection

@section('content')
<div class="card card-primary" id="page-wrap">
    <div class="card-header">
      <h3 class="card-title">{{__('General')}}</h3>
    </div>
    <form method="POST" action="{{route('admin.normal_range_heading.store')}}"  enctype="multipart/form-data"  id="form">
        <!-- /.card-header -->
        <div class="card-body">
            @csrf
            @include('admin.normal_range_heading._form')
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">{{__('Save')}}</button>
        </div>
    </form>	

</div>
 
@endsection
@section('scripts')
  <script src="{{url('public/js/admin/normal_range_heading.js')}}"></script>
@endsection

resources/views/admin/normal_range_heading/edit.blade.php
@extends('layouts.app')

@section('title')
{{__('Edit Normal Range Heading')}}
@endsection

@section('breadcrumb')

<div class="content-header">
    <div class="container-fluid" id="myHeaderLinks">
      <div class="row mb-2">
        <div class="col-sm-12">
          <h1 class="m-0 text-dark">
            <i class="nav-icon fas fa-user-injured"></i>
            {{__('Normal Range Headings')}}
          </h1>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
@endsection

@section('content')
<div class="card card-primary">
    <div class="card-header">
      <h3 class="card-title">{{__('Edit Normal Range Heading')}}</h3>
    </div>
    <!-- /.card-header -->
    <form method="POST" action="{{route('admin.normal_range_heading.update',$patient->id)}}"  enctype="multipart/form-data"  id="form">
        <!-- /.card-header -->
        <div class="card-body">
            @csrf
            @method('put')
            @include('admin.normal_range_heading._form')
        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">{{__('Save')}}</button>
        </div>
    </form>
    <!-- /.card-body -->
  </div>

 
@endsection
@section('scripts')
  <script src="{{url('public/js/admin/normal_range_heading.js')}}"></script> 
@endsection

resources/views/admin/normal_range_heading/index.blade.php
@extends('layouts.app')

@section('title')
{{__('Normal Range Headings')}}
@endsection

@section('breadcrumb')
<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark">
            <i class="nav-icon fas fa-user-injured"></i>
            {{__('Normal Range Headings')}}
          </h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{route('admin.index')}}">{{__('Home')}}</a></li>
            <li class="breadcrumb-item active">{{__('Normal Range Headings')}}</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
@endsection

@section('content')
<div class="card card-primary card-outline">
    <div class="card-header">
      <h3 class="card-title">{{__('Normal Range Headings Table')}}</h3>
      @can('create_patient')
      <a href="{{route('admin.normal_range_heading.create')}}" class="btn btn-primary btn-sm float-right">
       <i class="fa fa-plus"></i> {{__('Create')}} 
      </a>
      @endcan
    </div>
    <!-- /.card-header -->
    <div class="card-body">
     
	 {{--
      <div class="row">
        <div class="col-lg-12">
          <!-- Tools -->
          <div id="accordion">
            <div class="card card-info">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" class="btn btn-primary collapsed" aria-expanded="false">
                <i class="fas fa-file-excel"></i>
                {{__('Import / Export')}}
              </a>
              <div id="collapseOne" class="panel-collapse in collapse">
                <div class="card-body">
                  <div class="row">
                    <div class="col-lg-12 text-center">
                      <a class="btn btn-success" href="{{route('admin.normal_range_heading.export')}}">
                        <i class="fa fa-file-excel"></i>
                        {{__('Export')}}
                      </a>
                      <a class="btn btn-success" href="{{route('admin.normal_range_heading.download_template')}}">
                        <i class="fa fa-file-excel"></i>
                        {{__('Download template')}}
                      </a>
                    </div>
                    <div class="col-lg-12">
                      <!-- import form -->
                      <form action="{{route('admin.normal_range_heading.import')}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="row mt-3">
                          <div class="col-lg-12">
                            <div class="card card-primary">
                              <div class="card-header">
                                <h5 class="card-title">
                                    {{__('Import')}}
                                </h5>
                              </div>
                              <div class="card-body">
                                <div class="input-group">
                                  <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="exampleInputFile" name="import" required>
                                    <label class="custom-file-label" for="exampleInputFile">{{__('Choose file')}}</label>
                                  </div>
                                </div>
                              </div>
                              <div class="card-footer">
                                <button type="submit" class="btn btn-primary">
                                  <i class="fa fa-check"></i>
                                  {{__('Import')}}
                                </button>
                              </div>
                            </div>
                          </div>
                        </div>
                      </form>
                      <!-- /import form -->
                    </div>
                    
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- \Tools -->
        </div>
      </div>

	  --}}
      <div class="row">
        <div class="col-lg-12 table-responsive">
          <table id="table" class="table table-striped table-hover table-bordered display" width="100%">
            <thead>
            <tr>
              <th>ID#</th>
              <th>{{__('Name (English)')}}</th>
              <th>{{__('Name (Local)')}}</th>
              <th>{{__('Status')}}</th>
              <th width="100px">{{__('Action')}}</th>
            </tr>
            </thead>
            <tbody>
                
            </tbody>
          </table>

        </div>
      </div>
    </div>
    <!-- /.card-body -->
  </div>

@endsection
@section('scripts')
  <script src="{{url('public/js/admin/normal_range_heading.js')}}"></script>
@endsection