routes/admin.php
    Route::resource('faranchise_price_list','FaranchisePriceListController');
    Route::get('get_faranchise_price_list','FaranchisePriceListController@ajax')->name('faranchise_price_list');

    //Faranchise Registration Price List
    Route::resource('faranchise_price_list_discount','FaranchisePriceListDiscountController');


    //departments
    Route::resource('departments','DepartmentsController');
    Route::get('get_departments','DepartmentsController@ajax')->name('get_departments');
    Route::get('departments_export','DepartmentsController@export')->name('departments.export');
    Route::get('departments_download_template','DepartmentsController@download_template')->name('departments.download_template');
    Route::post('departments_import','DepartmentsController@import')->name('departments.import');

    //specialization
    Route::resource('specializations','SpecializationsController');
    Route::get('get_specializations','SpecializationsController@ajax')->name('get_specializations');
    Route::get('specializations_export','SpecializationsController@export')->name('specializations.export');
    Route::get('specializations_download_template','SpecializationsController@download_template')->name('specializations.download_template');
    Route::post('specializations_import','SpecializationsController@import')->name('specializations.import');

    //organizations
    Route::resource('organizations','OrganizationController');
    Route::get('get_organizations','OrganizationController@ajax')->name('get_organizations');
    Route::get('organizations_export','OrganizationController@export')->name('organizations.export');
    Route::get('organizations_download_template','OrganizationController@download_template')->name('organizations.download_template');
    Route::post('organizations_import','OrganizationController@import')->name('organizations.import');

    //cultures
    Route::resource('cultures','CulturesController');
    Route::get('get_cultures','CulturesController@ajax')->name('get_cultures');//datatable

    //culture options
    Route::resource('culture_options','CultureOptionsController');
    Route::get('get_culture_options','CultureOptionsController@ajax')->name('culture_options.ajax');

    //groups
    Route::resource('groups','GroupsController');
    Route::post('groups/send_receipt_mail/{id}','GroupsController@send_receipt_mail')->name('groups.send_receipt_mail');
    Route::post('groups/delete_analysis/{id}','GroupsController@delete_analysis');
    Route::get('get_groups','GroupsController@ajax')->name('get_groups');
    Route::get('get_search','GroupsController@ajax_search')->name('get_search');
    Route::get('get_requested_invoices_search','GroupsController@ajax_requested_search')->name('get_requested_invoices_search');
    Route::get('searching','GroupsController@searching')->name('searching');
    Route::get('invoice_statuses','GroupsController@invoice_statuses')->name('invoice_statuses');
    Route::get('invoice_cancel_req/{id?}','GroupsController@invoice_cancel_req')->name('invoice_cancel_req');
    Route::post('groups/request_for_cancel','GroupsController@request_for_cancel')->name('groups.request_for_cancel');
    Route::post('groups/print_barcode/{group_id}','GroupsController@print_barcode')->name('groups.print_barcode');

    //groups_credits
    Route::resource('groups_credits','GroupsCreditsController');
    Route::post('groups_credits/send_receipt_mail/{id}','GroupsCreditsController@send_receipt_mail')->name('groups_credits.send_receipt_mail');
    Route::post('groups_credits/delete_analysis/{id}','GroupsCreditsController@delete_analysis');
    Route::get('get_groups_credits','GroupsCreditsController@ajax')->name('get_groups_credits');
    Route::post('groups_credits/print_barcode/{group_id}','GroupsCreditsController@print_barcode')->name('groups_credits.print_barcode');

    //doctors
    Route::resource('doctors','DoctorsController');
    Route::get('get_doctors','DoctorsController@ajax')->name('get_doctors');
    Route::get('doctors_export','DoctorsController@export')->name('doctors.export');
    Route::get('doctors_download_template','DoctorsController@download_template')->name('doctors.download_template');
    Route::post('doctors_import','DoctorsController@import')->name('doctors.import');

    //test_registration
    Route::resource('test_registration','TestRegistrationController');
    Route::get('get_test_registration','TestRegistrationController@ajax')->name('get_test_registration');

	//doctors qualifications
	Route::resource('doctorsqualifications','DoctorsQualificationsController');
    Route::get('get_doctors_qualifications','DoctorsQualificationsController@ajax')->name('get_doctors_qualifications');
    Route::post('get_details','DoctorsQualificationsController@get_details')->name('get_details');

	//doctors expertises
	Route::resource('doctorsexpertises','DoctorsExpertisesController');
    Route::get('get_doctors_expertises','DoctorsExpertisesController@ajax')->name('get_doctors_expertises');
    Route::post('get_details_expertises','DoctorsExpertisesController@get_details')->name('get_details_expertises');

	//doctors charges
	Route::resource('doctorscharges','DoctorsChargesController');
    Route::get('get_doctors_charges','DoctorsChargesController@ajax')->name('get_doctors_charges');
    Route::post('get_details_charges','DoctorsChargesController@get_details')->name('get_details_charges');

	//reports
    Route::resource('reports','ReportsController');
    Route::post('reports/pdf/{id}','ReportsController@pdf')->name('reports.pdf');
    Route::post('reports/update_culture/{id}','ReportsController@update_culture')->name('reports.update_culture');//update cultures
    Route::get('get_reports','ReportsController@ajax')->name('get_reports');
    Route::get('sign_report/{id}','ReportsController@sign')->name('reports.sign');
    Route::post('reports/send_report_mail/{id}','ReportsController@send_report_mail')->name('reports.send_report_mail');


    //roles
    Route::resource('roles','RolesController');
    Route::get('get_roles','RolesController@ajax')->name('get_roles');

    //users
    Route::resource('users','UsersController');
    Route::get('get_users','UsersController@ajax')->name('get_users');

    //tests price list
    Route::get('prices/tests','PricesController@tests')->name('prices.tests');
    Route::post('prices/tests','PricesController@tests_submit')->name('prices.tests_submit');
    Route::get('tests_prices_export','PricesController@tests_prices_export')->name('prices.tests_prices_export');
    Route::post('tests_prices_import','PricesController@tests_prices_import')->name('prices.tests_prices_import');

    //cultures price list
    Route::get('prices/cultures','PricesController@cultures')->name('prices.cultures');
    Route::post('prices/cultures','PricesController@cultures_submit')->name('prices.cultures_submit');
    Route::get('cultures_prices_export','PricesController@cultures_prices_export')->name('prices.cultures_prices_export');
    Route::post('cultures_prices_import','PricesController@cultures_prices_import')->name('prices.cultures_prices_import');

    //accounting reports
    Route::get('accounting','AccountingController@index')->name('accounting.index');
    Route::get('generate_report','AccountingController@generate_report')->name('accounting.generate_report');
    Route::get('doctor_report','AccountingController@doctor_report')->name('accounting.doctor_report');
    Route::get('generate_doctor_report','AccountingController@generate_doctor_report')->name('accounting.generate_doctor_report');

    //chat
    Route::get('chat','ChatController@index')->name('chat.index');

    //visits
    Route::resource('visits','VisitsController');
    Route::get('visits/create_tests/{id}','VisitsController@create_tests')->name('visits.create_tests');
    Route::get('get_visits','VisitsController@ajax')->name('get_visits');

    //branches
    Route::resource('branches','BranchesController');
    Route::get('get_branches','BranchesController@ajax')->name('get_branches');

    //contracts
    Route::resource('contracts','ContractsController');
    Route::get('get_contracts','ContractsController@ajax')->name('get_contracts');

    //expenses
    Route::resource('expenses','ExpensesController');
    Route::get('get_expenses','ExpensesController@ajax')->name('get_expenses');

    //expense categories
    Route::resource('expense_categories','ExpenseCategoriesController');
    Route::get('get_expense_categories','ExpenseCategoriesController@ajax')->name('get_expense_categories');

    //backups
    Route::resource('backups','BackupsController');

    //reporting
    Route::group(['prefix'=>'reporting','as'=>'reporting.'],function(){
        Route::get('customer_registrations','ReportingController@customer_registrations')->name('customer_registrations');
        Route::get('inactive_patients','ReportingController@inactive_patients')->name('inactive_patients');
        Route::get('daily_cash_reporting','ReportingController@daily_cash_reporting')->name('daily_cash_reporting');
        Route::get('daily_credit_reporting','ReportingController@daily_credit_reporting')->name('daily_credit_reporting');
        Route::get('patient_visit_report','ReportingController@patient_visit_report')->name('patient_visit_report');
    });

    //activity logs
    Route::resource('activity_logs','ActivityLogsController');
    Route::post('activity_logs_clear','ActivityLogsController@clear')->name('activity_logs.clear');
    Route::get('get_activity_logs','ActivityLogsController@ajax')->name('get_activity_logs');

    //settings
    Route::group(['prefix'=>'settings','as'=>'settings.'],function(){
        Route::get('/','SettingsController@index')->name('index');
        Route::post('info','SettingsController@info_submit')->name('info_submit');
        Route::post('emails','SettingsController@emails_submit')->name('emails_submit');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware'=>['Install','Locale']],function(){
  include('admin.php');
  include('ajax.php');
  include('patient.php');
});

Route::get('change_locale/{lang}','HomeController@change_locale')->name('change_locale');

Route::get('clear-cache',function(){
  \Artisan::call('cache:clear');
  \Artisan::call('config:clear');
  \Artisan::call('view:clear');
});

resources/views/admin/groups_credits/_action.blade.php
<div class="dropdown">
    <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fa fa-cog"></i>
    </button>
    
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      
       @can('edit_group')
          <a href="{{route('admin.groups_credits.edit',$group['id'])}}" class="dropdown-item">
             <i class="fa fa-edit"></i>
             {{__('Edit')}}
          </a>
       @endcan

       @can('view_group')
         <a style="cursor: pointer" data-toggle="modal" data-target="#print_barcode_modal" class="dropdown-item print_barcode" group_id="{{$group['id']}}">
         <i class="fa fa-barcode" aria-hidden="true"></i>
         {{__('Print barcode')}}
         </a>
         <a href="{{route('admin.groups_credits.show',$group['id'])}}" class="dropdown-item">
            <i class="fa fa-print" aria-hidden="true"></i>
            {{__('Show Receipt')}}
         </a>
         @if($whatsapp['receipt']['active']&&isset($group['receipt_pdf']))
         <a target="_blank" href="{{whatsapp_notification($group,'receipt')}}" class="dropdown-item">
            <i class="fab fa-whatsapp" aria-hidden="true" class="text-success"></i>
            {{__('Send Receipt')}}
         </a>
         @endif
         @if($email['receipt']['active']&&isset($group['receipt_pdf']))
         <form action="{{route('admin.groups_credits.send_receipt_mail',$group['id'])}}" method="POST" class="d-inline">
            @csrf
            <button type="submit" class="dropdown-item">
               <i class="fa fa-envelope" aria-hidden="true" class="text-success"></i>
               {{__('Send Receipt')}}
            </button>
         </form>
         @endif
       @endcan
       
       @can('edit_report')
         <!--<a href="{{route('admin.reports.edit',$group['id'])}}" class="dropdown-item">
            <i class="fa fa-flask"></i>
            {{__('Enter results')}}
         </a>-->
       @endcan

       @can('delete_group')
          <form method="POST" action="{{route('admin.groups_credits.destroy',$group['id'])}}" class="d-inline">
             <input type="hidden" name="_method" value="delete">
             <a href="#" class="dropdown-item delete_group">
                <i class="fa fa-trash"></i>
                {{__('Delete')}}
             </a>
          </form>
       @endcan
    </div>
 </div>

resources/views/admin/groups_credits/_due.blade.php
@if($group['due']>0)
    <span class="text-danger text-bold">
        {{formated_price($group['due'])}}
    </span>
@else 
    <span class="text-success">
        {{formated_price($group['due'])}}
    </span>
@endif

resources/views/admin/groups_credits/_status.blade.php
@if($group['done'])
    <div class="text-center"><i class="fa fa-check-double text-success"></i></div>
@else
    <div class="text-center"><i class="fa fa-times-circle text-danger"></i></div>
@endif

resources/views/admin/groups_credits/create.blade.php
@extends('layouts.app')

@section('title')
    {{__('Create invoice')}}
@endsection

@section('breadcrumb')
<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
		 <div class="col-md-2">
			  <h1 class="m-0 text-dark">
				<i class="nav-icon fas fa-layer-group"></i>
				{{__('Invoices')}}
			  </h1>	
		  </div>
		  
		  <div class="col-md-10">
			  <ol class="breadcrumb customOl float-right">
				<li class="breadcrumb-item"><a href="#general_informaion"> <i class="nav-icon fas fa-user"></i> {{__('Register New Patient')}}</a></li>
				<li class="breadcrumb-item"><a href="{{route('admin.patients.index')}}"><i class="nav-icon fas fa-list"></i>{{__('View List')}}</a></li>
				<li class="breadcrumb-item"><a href="#emergency_contact"><i class="nav-icon fas fa-plane"></i>{{__('Travel History')}}</a></li>
				<li class="breadcrumb-item noBgBlue"><a href="#patient_documents"><i class="nav-icon fas fa-home"></i>{{__('Home')}}</a></li>
				<li class="breadcrumb-item noBgRed"><a href="#patient_documents"><i class="nav-icon fas fa-close"></i>{{__('Cancel Invoice')}}</a></li>
				<li class="breadcrumb-item"><a href="#patient_documents"><i class="nav-icon fas fa-plane"></i>{{__('Airline')}}</a></li>
				<li class="breadcrumb-item"><a href="#patient_documents"><i class="nav-icon fas fa-flag"></i>{{__('Country')}}</a></li>
				<li class="breadcrumb-item btn-danger"><a href="#patient_documents"><i class="nav-icon fas fa-print"></i>{{__('Invoice')}}</a></li>
			  </ol>
		  </div>
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
@endsection

@section('content')
   
   <!-- Form -->
   <form action="{{route('admin.groups_credits.store')}}" method="POST" id="group_form">
    @csrf
    @include('admin.groups_credits._form')
   </form>
   <!-- \Form -->

   <!-- Models -->
   @include('admin.groups_credits.modals.patient_modal')
   @include('admin.groups_credits.modals.doctor_modal')
   <!--\Models-->


@endsection

@section('scripts')
  <script src="{{url('public/js/admin/groups.js')}}"></script>
@endsection

resources/views/admin/groups_credits/edit.blade.php
@extends('layouts.app')

@section('title')
    {{__('Edit invoice')}}
@endsection

@section('breadcrumb')
<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark">
            <i class="nav-icon fas fa-layer-group"></i>
            {{__('Invoices')}}
          </h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{route('admin.index')}}">{{__('Home')}}</a></li>
            <li class="breadcrumb-item"><a href="{{route('admin.groups_credits.index')}}">{{__('Groups')}}</a></li>
            <li class="breadcrumb-item active">{{__('Edit invoice')}}</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
@endsection

@section('content')
   
   <!-- Form -->
   <form action="{{route('admin.groups_credits.update',$group->id)}}" method="POST" id="group_form">
        @csrf
        @method('put')
        @include('admin.groups_credits._form')
   </form>
   <!-- \Form -->

   <!-- Models -->
   @include('admin.groups_credits.modals.patient_modal')
   @include('admin.groups_credits.modals.doctor_modal')
   <!--\Models-->


@endsection

@section('scripts')
  <script>
    var test_arr=[];
    var culture_arr=[];

    (function($){

      "use strict";

      //selected tests
      @foreach($group['tests'] as $test)
        test_arr.push('{{$test["test_id"]}}');
      @endforeach

      //selected cultures
      @foreach($group['cultures'] as $culture)
        culture_arr.push('{{$culture["culture_id"]}}');
      @endforeach

    })(jQuery);
  </script>
  <script src="{{url('js/admin/groups_credits.js')}}"></script>
@endsection

resources/views/admin/groups_credits/index.blade.php
@extends('layouts.app')

@section('title')
{{__('Invoices')}}
@endsection

@section('breadcrumb')
<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark">
            <i class="nav-icon fas fa-layer-group"></i>
            {{__('Credits Sales/Invoices')}}
          </h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{route('admin.index')}}">{{__('Home')}}</a></li>
            <li class="breadcrumb-item active">{{__('Groups')}}</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
@endsection

@section('content')
<div class="card card-primary card-outline">
    <div class="card-header">
      <h3 class="card-title">{{__('Credits Sales/Invoices Table')}}</h3>
      <a href="{{route('admin.groups_credits.create')}}" class="btn btn-primary btn-sm float-right">
       <i class="fa fa-plus"></i> {{__('Create')}} 
      </a>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
	
    <!-- filter 
      <div id="accordion">
        <div class="card card-info">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" class="btn btn-primary collapsed" aria-expanded="false">
            <i class="fas fa-filter"></i> {{__('Filters')}}
          </a>
          <div id="collapseOne" class="panel-collapse in collapse">
            <div class="card-body">
              <div class="row justify-content-center">
                <div class="col-lg-3">
                  <div class="form-group">
                     <label for="filter_date">{{__('Date')}}</label>
                     <input type="text" class="form-control datepickerrange" id="filter_date" placeholder="{{__('Date')}}">
                  </div>
                </div>
                <div class="col-lg-3">
                  <div class="form-group">
                     <label for="filter_status">{{__('Status')}}</label>
                     <select name="filter_status" id="filter_status" class="form-control select2">
                        <option value="" selected>{{__('All')}}</option>
                        <option value="1">{{__('Done')}}</option>
                        <option value="0">{{__('Pending')}}</option>
                     </select>
                  </div>
                </div>
                <div class="col-lg-3">
                  <div class="form-group">
                     <label for="filter_barcode">{{__('Barcode')}}</label>
                     <input type="text" class="form-control" id="filter_barcode" placeholder="{{__('Barcode')}}">
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
	-->
	
    <!-- \filter -->
      <div class="row">
         <div class="col-lg-12 table-responsive">
            <table id="groups_table" class="table table-striped table-hover table-bordered" width="100%">
               <thead>
               <tr>
                 <th width="10px">#</th>
                 <th width="10px">{{__('Barcode')}}</th>
                 <th width="100px">{{__('Patient Code')}}</th>
                 <th>{{__('Patient Name')}}</th>
                 <th width="100px">{{__('Subtotal')}}</th>
                 <th width="100px">{{__('Discount')}}</th>
                 <th width="100px">{{__('Total')}}</th>
                 <th width="100px">{{__('Paid')}}</th>
                 <th width="100px">{{__('Due')}}</th>
                 <th width="100px">{{__('Date')}}</th>
                 <th width="10px">{{__('Status')}}</th>
                 <th width="50px">{{__('Action')}}</th>
               </tr>
               </thead>
               <tbody>
                 
               </tbody>
             </table>
         </div>
      </div>
    </div>
    <!-- /.card-body -->
  </div>

  @include('admin.groups_credits.modals.print_barcode')

@endsection
@section('scripts')
   <script src="{{url('public/js/select2.js')}}"></script>
   <script src="{{url('public/js/admin/groups_credits.js')}}"></script>
@endsection