routes/admin.php
<?php

//login admin
Route::group(['namespace'=>'Auth','prefix'=>'admin/auth','middleware'=>'AdminGuest','as'=>'admin.auth.'],function(){
    Route::get('/login','AdminController@login')->name('login');
    Route::post('/login','AdminController@login_submit')->name('login_submit');
});
//logout admin
Route::post('admin/logout','Auth\AdminController@logout')->name('admin.logout')->middleware('Admin');

//reset admin users password
Route::group(['namespace'=>'Auth','prefix'=>'admin/reset','as'=>'admin.reset.'],function(){
    Route::get('/mail','AdminController@mail')->name('mail');
    Route::post('/mail_submit','AdminController@mail_submit')->name('mail_submit');
    Route::get('/reset_password_form/{token}','AdminController@reset_password_form')->name('reset_password_form');
    Route::post('/reset_password_submit','AdminController@reset_password_submit')->name('reset_password_submit');
});

//admin controls
Route::group(['prefix'=>'admin','as'=>'admin.','namespace'=>'Admin','middleware'=>'Admin'],function(){
    //dashboard
    Route::get('/','IndexController@index')->name('index');

    //dashboard
    Route::resource('tests','TestsController');

    //profile
    Route::group(['prefix'=>'profile','as'=>'profile.'],function(){
        Route::get('edit','ProfileController@edit')->name('edit');
        Route::post('update','ProfileController@update')->name('update');
    });

    //tests and its components
    Route::resource('tests','TestsController');
    Route::get('get_tests','TestsController@ajax')->name('get_tests');//datatable

    //countries
    Route::resource('countries','CountriesController');
    Route::post('get_country_details','CountriesController@ajax')->name('get_country_details');

    //antibiotics
    Route::resource('antibiotics','AntibioticsController');
    Route::get('get_antibiotics','AntibioticsController@ajax')->name('get_antibiotics');

    //patients
    Route::resource('patients','PatientsController');
    Route::get('get_patients','PatientsController@ajax')->name('get_patients');
    Route::get('patients_export','PatientsController@export')->name('patients.export');
    Route::get('patients_download_template','PatientsController@download_template')->name('patients.download_template');
    Route::post('patients_import','PatientsController@import')->name('patients.import');

    //labs
    Route::resource('labs','LabsController');
    Route::get('get_labs','LabsController@ajax')->name('get_labs');
    Route::post('get_lab_centers','LabsController@get_lab_centers')->name('get_lab_centers');
    Route::get('labs_export','LabsController@export')->name('labs.export');
    Route::get('labs_download_template','LabsController@download_template')->name('labs.download_template');
    Route::post('labs_import','LabsController@import')->name('labs.import');

    //Airlines
    Route::resource('airlines','AirlinesController');
    Route::get('get_airlines','AirlinesController@ajax')->name('get_airlines');
    Route::get('labs_export','AirlinesController@export')->name('airlines.export');
    Route::get('labs_download_template','AirlinesController@download_template')->name('airlines.download_template');
    Route::post('labs_import','AirlinesController@import')->name('airlines.import');

	//Discount Role
    Route::resource('discountrole','DiscountRoleController');
    Route::get('get_discountrole','DiscountRoleController@ajax')->name('get_discountrole');
    Route::get('discountrole_export','DiscountRoleController@export')->name('discountrole.export');
    Route::get('discountrole_download_template','DiscountRoleController@download_template')->name('discountrole.download_template');
    Route::post('discountrole_import','DiscountRoleController@import')->name('discountrole.import');

    //centers
    Route::resource('centers','CentersController');
    Route::get('get_centers','CentersController@ajax')->name('get_centers');
    Route::get('centers_export','CentersController@export')->name('centers.export');
    Route::get('centers_download_template','CentersController@download_template')->name('centers.download_template');
    Route::post('centers_import','CentersController@import')->name('centers.import');

    //Test Unit
    Route::resource('units','UnitsController');
    Route::get('get_units','UnitsController@ajax')->name('get_units');
    Route::get('units_export','UnitsController@export')->name('units.export');
    Route::get('units_download_template','UnitsController@download_template')->name('units.download_template');
    Route::post('units_import','CentersController@import')->name('units.import');

    //Faranchises
    Route::resource('faranchises','FaranchisesController');
    Route::get('get_faranchises','FaranchisesController@ajax')->name('get_faranchises');
    Route::get('faranchises_export','FaranchisesController@export')->name('faranchises.export');
    Route::get('faranchises_download_template','FaranchisesController@download_template')->name('faranchises.download_template');
    Route::post('faranchises_import','FaranchisesController@import')->name('faranchises.import');

    //Supervisors Shift
    Route::resource('supervisorshift','SupervisorshiftController');
    Route::get('get_supervisorshift','SupervisorshiftController@ajax')->name('get_supervisorshift');
    Route::get('supervisorshift_export','SupervisorshiftController@export')->name('supervisorshift_export');
    Route::get('supervisorshift_download_template','SupervisorshiftController@download_template')->name('supervisorshift.download_template');
    Route::post('supervisorshift_import','SupervisorshiftController@import')->name('supervisorshift.import');

    //Users Shift
    Route::resource('usershift','UsershiftController');
    Route::get('get_usershift','UsershiftController@ajax')->name('usershift');
    Route::get('usershift_export','UsershiftController@export')->name('usershift_export');
    Route::get('usershift_download_template','UsershiftController@download_template')->name('usershift.download_template');
    Route::post('usershift_import','UsershiftController@import')->name('usershift.import');

    //Sample
    Route::resource('sample','SampleController');
    Route::get('get_sample','SampleController@ajax')->name('sample');

    //Patterns
    Route::resource('pattern','PatternController');
    Route::get('get_pattern','PatternController@ajax')->name('pattern');
    Route::get('pattern_export','PatternController@export')->name('pattern_export');
    Route::get('pattern_download_template','PatternController@download_template')->name('pattern.download_template');
    Route::post('pattern_import','PatternController@import')->name('pattern.import');

    //Age Classification
    Route::resource('age_classification','AgeClassificationController');
    Route::get('get_age_classification','AgeClassificationController@ajax')->name('age_classification');
    Route::get('age_classification_export','AgeClassificationController@export')->name('age_classification_export');
    Route::get('age_classification_download_template','AgeClassificationController@download_template')->name('age_classification.download_template');
    Route::post('age_classification_import','AgeClassificationController@import')->name('age_classification.import');

    //Normal Range Heading
    Route::resource('normal_range_heading','NormalRangeHeadingController');
    Route::get('get_normal_range_heading','NormalRangeHeadingController@ajax')->name('normal_range_heading');
    Route::get('normal_range_heading_export','NormalRangeHeadingController@export')->name('normal_range_heading_export');
    Route::get('normal_range_heading_download_template','NormalRangeHeadingController@download_template')->name('normal_range_heading.download_template');
    Route::post('normal_range_heading_import','NormalRangeHeadingController@import')->name('normal_range_heading.import');

	//Product Registration
    Route::resource('product_registration','ProductRegistrationController');
    Route::get('get_product_registration','ProductRegistrationController@ajax')->name('product_registration');
    Route::get('product_registration_export','ProductRegistrationController@export')->name('product_registration_export');
    Route::get('product_registration_download_template','ProductRegistrationController@download_template')->name('product_registration.download_template');
    Route::post('product_registration_import','ProductRegistrationController@import')->name('product_registration.import');

	//Morphology Registration
    Route::resource('morphology_registration','MorphologyRegistrationController');
    Route::get('get_morphology_registration','MorphologyRegistrationController@ajax')->name('morphology_registration');
    Route::get('morphology_registration_export','MorphologyRegistrationController@export')->name('morphology_registration_export');
    Route::get('morphology_registration_download_template','MorphologyRegistrationController@download_template')->name('morphology_registration.download_template');
    Route::post('morphology_registration_import','MorphologyRegistrationController@import')->name('morphology_registration.import');

	//CBC Remarks
    Route::resource('cbc_remarks','CbcRemarksController');
    Route::get('get_cbc_remarks','CbcRemarksController@ajax')->name('cbc_remarks');
    Route::get('cbc_remarks_export','CbcRemarksController@export')->name('cbc_remarks_export');
    Route::get('cbc_remarks_download_template','CbcRemarksController@download_template')->name('cbc_remarks.download_template');
    Route::post('cbc_remarks_import','CbcRemarksController@import')->name('cbc_remarks.import');

	// Package Registrations
    Route::resource('package_registrations','PackageRegistrationsController');
    Route::get('get_package_registrations','PackageRegistrationsController@ajax')->name('package_registrations');
    Route::get('package_registrations_export','PackageRegistrationsController@export')->name('package_registrations_export');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware'=>['Install','Locale']],function(){
  include('admin.php');
  include('ajax.php');
  include('patient.php');
});

Route::get('change_locale/{lang}','HomeController@change_locale')->name('change_locale');

Route::get('clear-cache',function(){
  \Artisan::call('cache:clear');
  \Artisan::call('config:clear');
  \Artisan::call('view:clear');
});

app/Models/Antibiotic.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\Traits\LogsActivity;

class Antibiotic extends Model
{
    use SoftDeletes;
    use LogsActivity;

    public $guarded=[];

    public $timestamps=false;

    public function getDescriptionForEvent(string $eventName): string
    {
        return "Antibiotic was {$eventName}";
    }
}

app/Http/Controllers/Admin/AntibioticsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Antibiotic;
use App\Http\Requests\Admin\AntibioticRequest;
use DataTables;

class AntibioticsController extends Controller
{
    /**
     * assign roles
     */
    public function __construct()
    {
        $this->middleware('can:view_antibiotic',     ['only' => ['index', 'show','ajax']]);
        $this->middleware('can:create_antibiotic',   ['only' => ['create', 'store']]);
        $this->middleware('can:edit_antibiotic',     ['only' => ['edit', 'update']]);
        $this->middleware('can:delete_antibiotic',   ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.antibiotics.index');
    }

    /**
    * get antibiotics datatable
    *
    * @access public
    * @var  @Request $request
    */
    public function ajax(Request $request)
    {
        $model=Antibiotic::query();

        return DataTables::eloquent($model)
        ->addColumn('action',function($antibiotic){
            return view('admin.antibiotics._action',compact('antibiotic'));
        })
        ->toJson();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.antibiotics.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AntibioticRequest $request)
    {
        Antibiotic::create($request->except('_token'));
        session()->flash('success','Antibiotic saved successfully');
        return redirect()->route('admin.antibiotics.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $antibiotic=Antibiotic::findOrFail($id);
        return view('admin.antibiotics.edit',compact('antibiotic'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AntibioticRequest $request, $id)
    {
        $antibiotic=Antibiotic::findOrFail($id);
        $antibiotic->update($request->except('_token','_method'));
        session()->flash('success','Antibiotic updated successfully');
        return redirect()->route('admin.antibiotics.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $antibiotic=Antibiotic::findOrFail($id);
        $antibiotic->delete();
        session()->flash('success','Antibiotic deleted successfully');
        return redirect()->route('admin.antibiotics.index');
    }
}

resources/views/admin/antibiotics/_action.blade.php
@can('edit_antibiotic')
<a href="{{route('admin.antibiotics.edit',$antibiotic['id'])}}" class="btn btn-primary btn-sm">
  <i class="fa fa-edit"></i>
</a>
@endcan

@can('delete_antibiotic')
<form method="POST" action="{{route('admin.antibiotics.destroy',$antibiotic['id'])}}" class="d-inline">
  <input type="hidden" name="_method" value="delete">
  <button type="submit" class="btn btn-danger btn-sm delete_antibiotic">
      <i class="fa fa-trash"></i>
  </button>
</form>
@endcan

resources/views/admin/antibiotics/_form.blade.php
<div class="row">
    <div class="col-lg-6">
     <div class="form-group">
      <label for="name">{{__('Name')}}</label>
      <input type="text" class="form-control" name="name" id="name" @if(isset($antibiotic)) value="{{$antibiotic->name}}" @endif required>
     </div>
    </div>
    <div class="col-lg-6">
       <div class="form-group">
        <label for="shortcut">{{__('Shortcut')}}</label>
        <input type="text" class="form-control" name="shortcut" id="shortcut" @if(isset($antibiotic)) value="{{$antibiotic->shortcut}}" @endif required>
       </div>
    </div>
    <div class="col-lg-12">
        <div class="form-group">
             <label for="commercial_name">{{__('Commercial Name')}}</label>
             <textarea name="commercial_name" id="commercial_name" rows="1" class="form-control" placeholder="{{__('Commercial Name')}}">@if(isset($antibiotic)){{$antibiotic['commercial_name']}}@endif</textarea>
        </div>
    </div>
</div>

resources/views/admin/antibiotics/create.blade.php
@extends('layouts.app')

@section('title')
{{__('Create Antibiotic')}}
@endsection

@section('css')
    <link rel="stylesheet" href="{{url('public/plugins/summernote/summernote-bs4.css')}}">
@endsection

@section('breadcrumb')
<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark">
            <h1 class="m-0 text-dark">
              <i class="nav-icon fas fa-capsules"></i>   
              {{__('Antibiotics')}}
            </h1>
          </h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{route('admin.index')}}">{{__('Home')}}</a></li>
            <li class="breadcrumb-item "><a href="{{route('admin.antibiotics.index')}}">{{__('Antibiotics')}}</a></li>
            <li class="breadcrumb-item active">{{__('Create antibiotic')}}</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
@endsection

@section('content')
<div class="card card-primary">
    <div class="card-header">
      <h3 class="card-title">{{__('Create Antibiotic')}}</h3>
    </div>
    <form method="POST" action="{{route('admin.antibiotics.store')}}">
        <!-- /.card-header -->
        <div class="card-body">
            @csrf
            @include('admin.antibiotics._form')
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">
              <i class="fa fa-check"></i> {{__('Save')}}
            </button>
        </div>
    </form>

</div>
@endsection
@section('scripts')
  <script src="{{url('js/admin/antibiotics.js')}}"></script>
@endsection

resources/views/admin/antibiotics/edit.blade.php
@extends('layouts.app')

@section('title')
{{__('Edit Antibiotic')}}
@endsection

@section('breadcrumb')
<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
            <h1 class="m-0 text-dark">
              <i class="nav-icon fas fa-capsules"></i>   
              {{__('Antibiotics')}}
            </h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{route('admin.index')}}">{{__('Home')}}</a></li>
            <li class="breadcrumb-item"><a href="{{route('admin.antibiotics.index')}}">{{__('Antibiotics')}}</a></li>
            <li class="breadcrumb-item active">{{__('Edit Antibiotic')}}</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
@endsection

@section('content')
<div class="card card-primary">
    <div class="card-header">
      <h3 class="card-title">{{__('Edit Antibiotic')}}</h3>
    </div>
    <!-- /.card-header -->
    <form method="POST" action="{{route('admin.antibiotics.update',$antibiotic->id)}}">
        <!-- /.card-header -->
        <div class="card-body">
            @csrf
            @method('put')
            @include('admin.antibiotics._form')
        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">
              <i class="fa fa-check"></i> {{__('Save')}}
            </button>
        </div>
    </form>
    <!-- /.card-body -->
  </div>

@endsection
@section('scripts')
  <script src="{{url('js/admin/antibiotics.js')}}"></script>
@endsection

resources/views/admin/antibiotics/index.blade.php
@extends('layouts.app')

@section('title')
{{__('Antibiotics')}}
@endsection

@section('breadcrumb')
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">
          <i class="nav-icon fas fa-capsules"></i>   
          {{__('Antibiotics')}}
        </h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{{route('admin.index')}}">{{__('Home')}}</a></li>
          <li class="breadcrumb-item active">{{__('Antibiotics')}}</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
@endsection

@section('content')
<div class="card card-primary card-outline">
  <div class="card-header">
    <h3 class="card-title">{{__('Antibiotics Table')}}</h3>
    @can('create_antibiotic')
    <a href="{{route('admin.antibiotics.create')}}" class="btn btn-primary btn-sm float-right">
     <i class="fa fa-plus"></i> {{__('Create')}}
    </a>
    @endcan
  </div>
  <!-- /.card-header -->
  <div class="card-body">
    <div class="row table-responsive">
      <div class="col-12">
        <table id="antibiotics_table" class="table table-striped table-hover table-bordered"  width="100%">
          <thead>
            <tr>
              <th width="10px">#</th>
              <th>{{__('Name')}}</th>
              <th>{{__('Shortcut')}}</th>
              <th>{{__('Commercial Name')}}</th>
              <th width="100px">{{__('Action')}}</th>
            </tr>
          </thead>
          <tbody>

          </tbody>
        </table>
      </div>
    </div>
  </div>
  <!-- /.card-body -->
</div>

@endsection
@section('scripts')
  <script src="{{url('js/admin/antibiotics.js')}}"></script>
@endsection